name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.20.x
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: CI Tasks
        run: make ci
